# Generated by Django 3.1.1 on 2020-10-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0007_auto_20201012_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morceau',
            name='artiste',
        ),
    ]
