# Generated by Django 3.2.8 on 2021-10-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0008_remove_morceau_artiste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
